### ISSUE TITLE
Details about the strongsort configs

### ISSUE THREAD

**Issue by yagelgen** [mikel-brostrom/Yolov7_StrongSORT_OSNet#3]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Is there more deep dive explanation about the configs of StrongSort?

I saw the following configs in `strong_sort.yaml`:

```
STRONGSORT:
  ECC: True              # activate camera motion compensation
  MC_LAMBDA: 0.995       # matching with both appearance (1 - MC_LAMBDA) and motion cost
  EMA_ALPHA: 0.9         # updates  appearance  state in  an exponential moving average manner
  MAX_DIST: 0.2          # The matching threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 0.7  # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 30            # Maximum number of missed misses before a track is deleted
  N_INIT: 3              # Number of frames that a track remains in initialization phase
  NN_BUDGET: 100         # Maximum size of the appearance descriptors gallery
```

But i'm not really understand most of the explanations.
I think more deep dive explanations can be really beneficial for less experts.
